
export const GET_DATASET = 'GET_DATASET';
export const GET_FEATURE = 'GET_FEATURE';

export const CREATE_FEATURE = 'CREATE_FEATURE';

export const CREATE_BUILDING = 'CREATE_BUILDING';
export const CREATE_BUILDING_ERR = 'CREATE_BUILDING_ERR';

export const GET_BUILDINGS = 'CREATE_BUILDING';
export const GET_BUILDING_ERR = 'CREATE_BUILDING_ERR';

export const CREATE_PARKING_LOT = 'CREATE_PARKING_LOT';
export const CREATE_PARKING_LOT_ERR = 'CREATE_PARKING_LOT_ERR';
