
export const GET_DATASET = 'GET_DATASET';
export const GET_FEATURE = 'GET_FEATURE';

export const CREATE_FEATURE = 'CREATE_FEATURE';

export const CREATE_BUILDING = 'CREATE_BUILDING';
export const CREATE_BUILDING_ERR = 'CREATE_BUILDING_ERR';
